# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36cd45a850256e2a2f0df774c133501233062f398b551baf8b6dc285dd178ba6c290052ae5f30e8c34b64dd1ba61c8bfbd27879881b48d5b85d306d63a0aa8f1

test:
  secret_key_base: 3e6f5ede82c61e4239ce7d7b8c29d88f734f634894fcb4f780fea14ac39571dd54a9fb7573de271fa5ef4a16077b76f49f411248941664db8b9c48f0e4611043

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
